{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c16ca47d-1b64-4452-89dd-408bb0c97c3b",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import pickle\n",
    "import numpy as np\n",
    "import plotly.graph_objects as go\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# -------------------------------\n",
    "# PAGE CONFIG (MUST BE FIRST)\n",
    "# -------------------------------\n",
    "st.set_page_config(\n",
    "    page_title=\"Yas Dubai South Dashboard\",\n",
    "    layout=\"wide\",\n",
    "    initial_sidebar_state=\"expanded\"\n",
    ")\n",
    "\n",
    "# -------------------------------\n",
    "# CONFIG\n",
    "# -------------------------------\n",
    "AREA_NAME = \"Al Khairan First\"\n",
    "MACRO_NEWS_FACTOR = 1.045  # Structural uplift\n",
    "\n",
    "# -------------------------------\n",
    "# LOAD ASSETS\n",
    "# -------------------------------\n",
    "@st.cache_resource\n",
    "def load_model():\n",
    "    with open(\"rf_model_Al Khairan First.pkl\", \"rb\") as f:\n",
    "        return pickle.load(f)\n",
    "\n",
    "@st.cache_resource\n",
    "def load_columns():\n",
    "    with open(\"trained_columns_Al Khairan First.pkl\", \"rb\") as f:\n",
    "        return pickle.load(f)\n",
    "\n",
    "model = load_model()\n",
    "training_columns = load_columns()\n",
    "\n",
    "growth_df = pd.read_csv(\"Sarima_forecast_6M.csv\")\n",
    "growth_df = growth_df[growth_df[\"area_name_en\"] == AREA_NAME]\n",
    "growth_df[\"month\"] = pd.to_datetime(growth_df[\"month\"])\n",
    "\n",
    "historical_df = pd.read_csv(\"historical_df.csv\")\n",
    "historical_df = historical_df[historical_df[\"area_name_en\"] == AREA_NAME]\n",
    "historical_df[\"month\"] = pd.to_datetime(historical_df[\"month\"])\n",
    "\n",
    "# -------------------------------\n",
    "# HISTORICAL MONTHLY AGGREGATION (CONNECTED)\n",
    "# -------------------------------\n",
    "monthly_hist_df = (\n",
    "    historical_df\n",
    "    .groupby(pd.Grouper(key=\"month\", freq=\"MS\"))\n",
    "    .agg(\n",
    "        median_price=(\"median_price\", \"median\"),\n",
    "        count=(\"median_price\", \"count\")\n",
    "    )\n",
    ")\n",
    "\n",
    "# Ensure continuous monthly timeline\n",
    "full_month_index = pd.date_range(\n",
    "    start=monthly_hist_df.index.min(),\n",
    "    end=monthly_hist_df.index.max(),\n",
    "    freq=\"MS\"\n",
    ")\n",
    "\n",
    "monthly_hist_df = monthly_hist_df.reindex(full_month_index)\n",
    "monthly_hist_df = monthly_hist_df.reset_index().rename(columns={\"index\": \"month\"})\n",
    "\n",
    "# -------------------------------\n",
    "# CATEGORIES\n",
    "# -------------------------------\n",
    "DEVELOPER_CATEGORIES = [\"Grade 1\", \"Others\"]\n",
    "\n",
    "PROJECT_CATEGORIES = [\n",
    "    \"Developer-Led Mid-Market\",\n",
    "    \"General / Unclassified\",\n",
    "    \"Parks & Eco-Living\",\n",
    "    \"Standard Residential\",\n",
    "    \"Investment & High-Volume\",\n",
    "    \"Urban High Rise\",\n",
    "    \"Ultra-Luxury & Premium\",\n",
    "    \"City Centric & Boulevards\",\n",
    "    \"Waterfront & Marine\",\n",
    "    \"Golf & Sports Lifestyle\",\n",
    "    \"Suburban & Gated Communities\",\n",
    "    \"Managed & Serviced\",\n",
    "    \"Modern & Concept Living\",\n",
    "    \"Scenic Views & Vistas\"\n",
    "]\n",
    "\n",
    "FLOOR_BINS = [\"0-10\", \"11-20\", \"21-30\", \"31-40\", \"41-50\"]\n",
    "\n",
    "ROOM_MAP = {\n",
    "    \"Studio\": \"Studio\",\n",
    "    \"1 B/R\": \"1 B/R\",\n",
    "    \"2 B/R\": \"2 B/R\",\n",
    "    \"3 B/R\": \"3 B/R\",\n",
    "    \"4 B/R\": \"4 B/R\",\n",
    "    \"5 B/R\": \"5 B/R\",\n",
    "    \"6 B/R\": \"6 B/R\"\n",
    "}\n",
    "\n",
    "REG_TYPE_MAP = [\"Off-Plan Properties\", \"Existing Properties \"]\n",
    "\n",
    "# -------------------------------\n",
    "# INPUT PREPARATION\n",
    "# -------------------------------\n",
    "def prepare_input(user_vals):\n",
    "    row = pd.DataFrame([user_vals])\n",
    "    for col in training_columns:\n",
    "        if col not in row.columns:\n",
    "            row[col] = 0\n",
    "    return row[training_columns]\n",
    "\n",
    "def anchor_prediction(last_hist, pred, max_dev=0.06):\n",
    "    upper = last_hist * (1 + max_dev)\n",
    "    lower = last_hist * (1 - max_dev)\n",
    "    return float(np.clip(pred, lower, upper))\n",
    "\n",
    "# -------------------------------\n",
    "# UI\n",
    "# -------------------------------\n",
    "st.title(\"📈 Yas Island Meter Sale Price Forecast\")\n",
    "\n",
    "st.caption(\n",
    "    \"Forecast combines historical pricing, model-based valuation, \"\n",
    "    \"organic market growth, and structural macro-event adjustments specific to Yas Island.\"\n",
    ")\n",
    "\n",
    "# -------------------------------\n",
    "# USER INPUTS\n",
    "# -------------------------------\n",
    "st.sidebar.header(\"Property Configuration\")\n",
    "\n",
    "rooms = st.sidebar.selectbox(\"Rooms\", list(ROOM_MAP.keys()), index=2)\n",
    "floor = st.sidebar.selectbox(\"Floor Range\", FLOOR_BINS, index=1)\n",
    "\n",
    "swimming_pool = st.sidebar.checkbox(\"Swimming Pool\", value=True)\n",
    "balcony = st.sidebar.checkbox(\"Balcony\", value=True)\n",
    "metro = st.sidebar.checkbox(\"Near Metro\", value=False)\n",
    "\n",
    "project_cat = st.sidebar.selectbox(\"Project Category\", PROJECT_CATEGORIES)\n",
    "developer_cat = st.sidebar.selectbox(\"Developer Category\", DEVELOPER_CATEGORIES)\n",
    "\n",
    "reg_type = st.sidebar.selectbox(\"Registration Type\", REG_TYPE_MAP, index=1)\n",
    "\n",
    "# -------------------------------\n",
    "# MODEL INPUT\n",
    "# -------------------------------\n",
    "model_input = {\n",
    "    \"reg_type_en\": reg_type,\n",
    "    \"rooms_en\": ROOM_MAP.get(rooms, \"2 B/R\"),\n",
    "    \"has_parking\": 1,\n",
    "    \"procedure_area\": 80,\n",
    "    \"land_type_en\": \"Commercial\",\n",
    "    \"floor_bin\": floor,\n",
    "    \"swimming_pool\": int(swimming_pool),\n",
    "    \"balcony\": int(balcony),\n",
    "    \"elevator\": 1,\n",
    "    \"metro\": int(metro),\n",
    "    \"project_cat\": project_cat,\n",
    "    \"developer_cat\": developer_cat\n",
    "}\n",
    "\n",
    "X = prepare_input(model_input)\n",
    "base_price = model.predict(X)[0]\n",
    "\n",
    "# -------------------------------\n",
    "# FORECAST CONSTRUCTION\n",
    "# -------------------------------\n",
    "forecast_df = growth_df.copy().sort_values(\"month\")\n",
    "\n",
    "forecast_df[\"baseline_price\"] = base_price * forecast_df[\"growth_factor\"]\n",
    "forecast_df[\"scenario_price (with macroeconomic features and news)\"] = (\n",
    "    forecast_df[\"baseline_price\"] * MACRO_NEWS_FACTOR\n",
    ")\n",
    "\n",
    "# -------------------------------\n",
    "# HISTORICAL DATA (RAW)\n",
    "# -------------------------------\n",
    "hist_df = monthly_hist_df.copy()\n",
    "\n",
    "last_hist_price = hist_df[\"median_price\"].dropna().iloc[-1]\n",
    "last_hist_date = hist_df.loc[\n",
    "    hist_df[\"median_price\"].last_valid_index(), \"month\"\n",
    "]\n",
    "\n",
    "# -------------------------------\n",
    "# ANCHOR PREDICTION\n",
    "# -------------------------------\n",
    "anchored_prediction = anchor_prediction(\n",
    "    last_hist=last_hist_price,\n",
    "    pred=base_price,\n",
    "    max_dev=0.06\n",
    ")\n",
    "\n",
    "# -------------------------------\n",
    "# REBASE FORECAST (NO SMOOTHING)\n",
    "# -------------------------------\n",
    "baseline_raw = anchored_prediction * (\n",
    "    forecast_df[\"baseline_price\"] / forecast_df[\"baseline_price\"].iloc[0]\n",
    ")\n",
    "\n",
    "scenario_raw = anchored_prediction * (\n",
    "    forecast_df[\"scenario_price (with macroeconomic features and news)\"]\n",
    "    / forecast_df[\"baseline_price\"].iloc[0]\n",
    ")\n",
    "\n",
    "forecast_df[\"baseline_smooth\"] = baseline_raw\n",
    "forecast_df[\"scenario_price (with macroeconomic features and news)\"] = scenario_raw\n",
    "\n",
    "# -------------------------------\n",
    "# PLOT\n",
    "# -------------------------------\n",
    "fig = go.Figure()\n",
    "\n",
    "# Historical line (CONNECTED)\n",
    "fig.add_trace(go.Scatter(\n",
    "    x=hist_df[\"month\"],\n",
    "    y=hist_df[\"median_price\"],\n",
    "    mode=\"lines+markers\",\n",
    "    name=\"Historical Monthly Median\",\n",
    "    connectgaps=True,\n",
    "    line=dict(width=3),\n",
    "    marker=dict(size=6)\n",
    "))\n",
    "\n",
    "# Model prediction connection\n",
    "fig.add_trace(go.Scatter(\n",
    "    x=[last_hist_date, forecast_df[\"month\"].iloc[0]],\n",
    "    y=[last_hist_price, anchored_prediction],\n",
    "    mode=\"lines+markers\",\n",
    "    name=\"Model Prediction\",\n",
    "    line=dict(width=2, dash=\"dot\"),\n",
    "    marker=dict(size=10)\n",
    "))\n",
    "\n",
    "# Baseline forecast\n",
    "fig.add_trace(go.Scatter(\n",
    "    x=forecast_df[\"month\"],\n",
    "    y=forecast_df[\"baseline_smooth\"],\n",
    "    mode=\"lines\",\n",
    "    name=\"Baseline Forecast\",\n",
    "    line=dict(width=3, dash=\"dash\")\n",
    "))\n",
    "\n",
    "# Scenario forecast\n",
    "fig.add_trace(go.Scatter(\n",
    "    x=forecast_df[\"month\"],\n",
    "    y=forecast_df[\"scenario_price (with macroeconomic features and news)\"],\n",
    "    mode=\"lines\",\n",
    "    name=\"Scenario Forecast\",\n",
    "    line=dict(width=4)\n",
    "))\n",
    "\n",
    "# -------------------------------\n",
    "# STYLING\n",
    "# -------------------------------\n",
    "fig.update_layout(\n",
    "    height=520,\n",
    "    xaxis_title=\"Month\",\n",
    "    yaxis_title=\"Meter Sale Price (AED)\",\n",
    "    hovermode=\"x unified\",\n",
    "    template=\"plotly_white\",\n",
    "    legend=dict(\n",
    "        orientation=\"h\",\n",
    "        yanchor=\"bottom\",\n",
    "        y=1.02,\n",
    "        xanchor=\"right\",\n",
    "        x=1\n",
    "    )\n",
    ")\n",
    "\n",
    "fig.update_xaxes(\n",
    "    dtick=\"M1\",\n",
    "    tickformat=\"%b %Y\",\n",
    "    tickangle=-45,\n",
    "    showgrid=True\n",
    ")\n",
    "\n",
    "fig.add_vrect(\n",
    "    x0=forecast_df[\"month\"].min(),\n",
    "    x1=forecast_df[\"month\"].max(),\n",
    "    fillcolor=\"lightblue\",\n",
    "    opacity=0.08,\n",
    "    layer=\"below\",\n",
    "    line_width=0\n",
    ")\n",
    "\n",
    "st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "# -------------------------------\n",
    "# EXPLANATION\n",
    "# -------------------------------\n",
    "st.subheader(\"🧠 Scenario Explanation\")\n",
    "\n",
    "st.write(f\"**Base Model Price:** {base_price:,.0f} AED / m²\")\n",
    "st.write(f\"**Structural Adjustment Applied:** +{(MACRO_NEWS_FACTOR-1)*100:.2f}%\")\n",
    "\n",
    "st.markdown(\n",
    "    \"\"\"\n",
    "**Scenario assumptions include:**\n",
    "- Major entertainment-led development in Yas Island\n",
    "- Tourism-driven demand expansion\n",
    "- Supporting infrastructure and hospitality investments\n",
    "- Stable regulatory and interest rate environment\n",
    "\"\"\"\n",
    ")\n",
    "\n",
    "# -------------------------------\n",
    "# DATA TABLE\n",
    "# -------------------------------\n",
    "with st.expander(\"📄 Forecast Data\"):\n",
    "    st.dataframe(\n",
    "        forecast_df[[\"month\", \"baseline_price\", \"scenario_price (with macroeconomic features and news)\"]]\n",
    "        .rename(columns={\n",
    "            \"baseline_price\": \"Baseline Forecast\",\n",
    "            \"scenario_price (with macroeconomic features and news)\": \"Scenario Forecast with macroeconomic and news data\"\n",
    "        })\n",
    "    )\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
